### ISSUE TITLE
Mesh direction and shaders (?) seem to be affected by the original mini

### ISSUE THREAD

**Issue by Feliphysics** [LordAshes/TaleSpire-FileAccessPlugin#2]
As can be seen in the screenshots below, custom minis' seem to be affected by the vanilla mini they were transformed from. While the shader (?) problem seem to only happen with ghosts (aka irrelevant) the direction is more widespread. The problem is consistent with old and new transformations. [direction of minis was not changed between screenshots, of course]

<img width="668" alt="kiki1" src="https://user-images.githubusercontent.com/87597484/126059824-d09b1cf3-1d6e-4000-9f50-97bf3ae6dc8d.png">

<img width="631" alt="kiki2" src="https://user-images.githubusercontent.com/87597484/126059817-cf8bcd4c-34e9-4b07-81d0-30ae6f074264.png">

**Comment by LordAshes** [comment]
Yes. Now that CMP is using mesh transfer, the originating mini size will
affect the transformed size. For now this is not a bug, it is "as
expected". I will look into the possibility of negating this but it is not
a high priority.
Yes. Transformed minis will now use the original mini Shader. This is the
TaleSpireCreature shader. This is "as designed".

I suggest finding mini of a regular size and regular shader settings and
using that for all transformed minis.

Lord Ashes


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Feliphysics** [comment]
I just noticed that in the 5.0.1 patchnote you wrote "corrected mini facing", if that is related to this issue it doesn't actually seem to be resolved. Anyway, if that is the price to pay in order to have a working Line of Sight it seems worth it to me, and the camel looks like a really valid option for now, having direction, size and shaders that seem to be for the most part "correct". (after the patch I noticed some of my minis facing the correct direction, but, once you move them, that stopped being the case)

**Comment by LordAshes** [comment]
This issue resolves the fact that when an mini was transformed, facing the
mini up would cause the transformed mini to be facing down (i.e. in the
opposite direction of facing). This has been corrected. A transformed mini
now faces in the direction of the mouse.

Lord Ashes

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Feliphysics** [comment]
In conclusion it looks like everything is following expected behaviour so no need for this issue to stay open, thanks a lot for the information and the help
